[pre-commit]
parallel = true

[pre-commit.commands.toml]
glob = "*.toml"
run = "pnpm taplo check {staged_files}"

[pre-commit.commands.check]
run = "pnpm check"
glob = "*.svelte"

[pre-commit.commands.lint]
glob = "*.{ts,svelte}"
run = "pnpm eslint --fix {staged_files} && git update-index --again"

[pre-commit.commands.format]
glob = "*.{ts,svelte,css,json}"
run = "pnpm prettier --write {staged_files} && git update-index --again"

[commit-msg.commands.commitlint]
run = "pnpm commitlint --edit $1"
